pull_request_rules:
  - name: Automatically merge successful flake updates
    conditions:
      - author=Lyndeno
      - title=Update flake.lock
      - "check-success~=nix-build"
    actions:
      merge:
        method: merge
  - name: Automatically merge dependabot updates
    conditions:
      - author=dependabot
      - "check-success~=nix-build"
    actions:
      merge:
        method: merge
