name: Build Flake

on:
  push:

  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build-nixos:
    strategy:
      matrix:
        host: [ neo, morpheus, oracle, trinity ]
      fail-fast: true
      max-parallel: 1
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Nuke packages
        run: |
          sudo rm -rf /usr/share /usr/local /opt || true
      - name: Install Nix
        uses: cachix/install-nix-action@v22
        with:
          extra_nix_config: |
            extra-platforms = aarch64-linux arm-linux i686-linux
      - name: Set up cachix
        uses: cachix/cachix-action@v12
        with:
          name: lyndeno
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - uses: DeterminateSystems/magic-nix-cache-action@v1
      - name: Install binfmt tools
        run: |
          DEBIAN_FRONTEND=noninteractive
          sudo apt-get update -q -y && sudo apt-get install -q -y qemu-system-aarch64 qemu-efi binfmt-support qemu-user-static
      - name: Build Nix Flake
        run: nix build .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel