name: Update Flake Inputs

on:
  schedule:
    - cron: '5 3 * * 0'

  workflow_dispatch:

jobs:
  update-flake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install Nix
        uses: cachix/install-nix-action@v22
        with:
          extra_nix_config: |
            extra-platforms = aarch64-linux arm-linux
      - name: Install binfmt tools
        run: |
          DEBIAN_FRONTEND=noninteractive
          sudo apt-get update -q -y && sudo apt-get install -q -y qemu-system-aarch64 qemu-efi binfmt-support qemu-user-static
      - name: Update Nix Flake Inputs
        run: nix flake update
      - name: Check Nix Flake
        run: nix flake check
      - name: Commit flake.lock
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: master
          commit_message: Update flake.lock
          commit_options: '--no-verify --signoff'
          file_pattern: flake.lock
          skip_dirty_check: false
          skip_fetch: true