name: Update Flake Inputs

on:
  schedule:
    - cron: '5 3 * * 0'

  workflow_dispatch:

jobs:
  update-flake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          extra_nix_config: |
            extra-platforms = aarch64-linux arm-linux
      - name: Update Nix Flake Inputs
        run: nix flake update
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7.0.8
        with:
          token: ${{ secrets.PTOKEN }}
          base: master
          branch: update/flake-update
          delete-branch: true
          commit-message: Update flake.lock
          title: Update flake.lock